spring.application.name=movies-app

# datasource
spring.datasource.url=jdbc:postgresql://localhost:15432/studs
spring.datasource.username=s367550
spring.datasource.password=Htplca1QwjFcBpNO

# HikariCP
spring.datasource.hikari.pool-name=MoviesHikariPool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# EclipseLink
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.eclipse.persistence.platform.database.PostgreSQLPlatform
spring.jpa.properties.javax.persistence.provider=org.eclipse.persistence.jpa.PersistenceProvider
spring.jpa.properties.eclipselink.logging.level=FINE
spring.jpa.properties.eclipselink.logging.parameters=true
spring.jpa.properties.eclipselink.weaving=false
spring.jpa.properties.eclipselink.cache.shared.default=true
spring.jpa.properties.eclipselink.cache.size.default=5000

# Flyway
spring.flyway.enabled=false

# JSON
spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false

spring.cache.type=jcache
spring.cache.jcache.config=classpath:ehcache.xml
spring.cache.jcache.provider=org.ehcache.jsr107.EhcacheCachingProvider

app.cache.stats-logging-enabled=false

app.minio.endpoint=http://localhost:9000
app.minio.bucket=movies-imports
app.minio.access-key=minioadmin
app.minio.secret-key=minioadmin
app.minio.region=us-east-1
app.minio.secure=false

server.port=8082
