spring.application.name=movies-app

# подключаемся через твой SSH-туннель
spring.datasource.url=jdbc:postgresql://localhost:15432/studs
spring.datasource.username=s367550
spring.datasource.password=Htplca1QwjFcBpNO

# EclipseLink
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.eclipse.persistence.platform.database.PostgreSQLPlatform
spring.jpa.properties.javax.persistence.provider=org.eclipse.persistence.jpa.PersistenceProvider
spring.jpa.properties.eclipselink.logging.level=FINE
spring.jpa.properties.eclipselink.logging.parameters=true
spring.jpa.properties.eclipselink.weaving=false
spring.jpa.properties.eclipselink.cache.shared.default=false

# ВАЖНО: отключаем Flyway, он тебе и падает
spring.flyway.enabled=false

# JSON
spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false


server.port=8082
